### ISSUE TITLE
Not compatible with latest go.opentelemetry.io/otel version(s)

### ISSUE THREAD

**Issue by Flo4604** [axiomhq/axiom-go#321]
same as #314

`2024/07/06 19:19:03 failed to create tracer provider: conflicting Schema URL: https://opentelemetry.io/schemas/1.26.0 and https://opentelemetry.io/schemas/1.25.0
`

Are there any plans on the approach of https://github.com/axiomhq/axiom-go/issues/314#issuecomment-2146016038

Since each other go module that depends on the newer versions of otel will result in confilicting schemas

**Comment by lukasmalkmus** [comment]
So https://github.com/axiomhq/axiom-go/blob/main/axiom/otel/trace.go#L103-L111 is causing all the problems here.

I re-reviewed how we're merging the resources there and observed the following bit in the resources GoDoc:

> _[...]_ if b's schema URL is empty then the returned Resource's schema URL will be set to the schema URL of a _[...]_

So **not** manually setting a schema for the second resource we create (in order to get the service information merged into the resource) should fix the problem you unfortunately observed twice in a rather short timespan (due to a fast release cadence of the `semconv` package). I have it a quick try by running [the example](examples/oteltraces) with a `semconv` version different from the one specified in the upstream default resource.

**Comment by lukasmalkmus** [comment]
I just tagged `v0.19.1`.

**Comment by Flo4604** [comment]
this solved it, thanks for the explanation and fixing it so soon!
